### ISSUE TITLE
i have problem when i run 

### ISSUE THREAD

**Issue by shadihh9** [0xL1mb0/Nakerah-lab-v1#1]
raceback (most recent call last):
  File "Nakerah-lab.py", line 198, in <module>
    doQuery(myConnection)
  File "Nakerah-lab.py", line 155, in doQuery
    cur.execute("create database dvwa;")
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 226, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1007, "Can't create database 'dvwa'; database exists")

**Comment by Limbo0x01** [comment]
i fixed it , all of this because the new kali version 2020  , or u already  had installed  DVWA before  . 
Anyway to fix this you  have two options   : 
1- Download the new script from the GitHub here .  and run it on a new kali or any linux system  " you never installed this script before on it ". 

OR 

2- Run this commands : 

sudo mysql -u root -proot
SHOW DATABASES;
DROP DATABASE dvwa;
DROP DATABASE xvwa;
DROP DATABASE bWAPP;
DROP DATABASE security;
DROP DATABASE challenges;
DROP DATABASE mutillidae;
DROP USER 'dvwa'@'localhost';
DROP USER 'xvwa'@'localhost';
DROP USER 'bWAPP'@'localhost';
DROP USER 'sql'@'localhost';
DROP USER 'mutillidae'@'localhost';
flush privileges;
exit;


sudo apt-get install git
sudo git clone https://github.com/0xL1mb0/Nakerah-lab-v1.git
cd Nakerah-lab-v1
sudo chmod +x setup.sh
sudo ./setup.sh

---------------------------------
Was because of sudo before ./setup.sh :3

**Comment by kSuccess** [comment]
I've this issues while running the script 

Using MySQLdb ... 
Traceback (most recent call last):
  File "Nakerah-lab.py", line 215, in <module>
    doQuery(myConnection)
  File "Nakerah-lab.py", line 172, in doQuery
    cur.execute("create database dvwa;")
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 226, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1007, "Can't create database 'dvwa'; database exists"

**Comment by Limbo0x01** [comment]
Can you please tell me what is the exact version of your operating system?

**Comment by kSuccess** [comment]
Ubuntu server 20.04

**Comment by Limbo0x01** [comment]
I will fix it in Ubuntu 20 ASAP , u can try Ubuntu 18 it will work fine

**Comment by mirage-F** [comment]
i just tryed in  ubunu 18.4  stile not working

**Comment by mirage-F** [comment]
it s  work for kali20.0  but  didn t with ubuntu

**Comment by Te0xte1** [comment]
I'm facing an issue too 
when i run mutillidae
it output this 


Fatal error: Uncaught Error: Call to undefined function simplexml_load_file() in /var/www/html/mutillidae/owasp-esapi-php/src/reference/DefaultSecurityConfiguration.php:136 Stack trace: #0 /var/www/html/mutillidae/owasp-esapi-php/src/reference/DefaultSecurityConfiguration.php(116): DefaultSecurityConfiguration->_loadConfiguration() #1 /var/www/html/mutillidae/owasp-esapi-php/src/ESAPI.php(362): DefaultSecurityConfiguration->__construct() #2 /var/www/html/mutillidae/owasp-esapi-php/src/ESAPI.php(66): ESAPI::getSecurityConfiguration() #3 /var/www/html/mutillidae/index.php(157): ESAPI->__construct() #4 {main} thrown in /var/www/html/mutillidae/owasp-esapi-php/src/reference/DefaultSecurityConfiguration.php on line 136

**Comment by Limbo0x01** [comment]
[SOLVED]

**Comment by sisi-nj** [comment]
please help  ,
mysqli::__construct(): (HY000/1698): Access denied for user 'root'@'localhost' in /var/www/html/mutillidae/classes/MySQLHandler.php
