### ISSUE TITLE
error when open mutillidae

### ISSUE THREAD

**Issue by samaa112** [0xL1mb0/Nakerah-lab-v1#3]
when I open mutillidae/ this error appears  thanks to help me solve it 

Fatal error: Uncaught Error: Call to undefined function simplexml_load_file() in /var/www/html/mutillidae/owasp-esapi-php/src/reference/DefaultSecurityConfiguration.php:136 Stack trace: #0 /var/www/html/mutillidae/owasp-esapi-php/src/reference/DefaultSecurityConfiguration.php(116): DefaultSecurityConfiguration->_loadConfiguration() #1 /var/www/html/mutillidae/owasp-esapi-php/src/ESAPI.php(362): DefaultSecurityConfiguration->__construct() #2 /var/www/html/mutillidae/owasp-esapi-php/src/ESAPI.php(66): ESAPI::getSecurityConfiguration() #3 /var/www/html/mutillidae/index.php(157): ESAPI->__construct() #4 {main} thrown in /var/www/html/mutillidae/owasp-esapi-php/src/reference/DefaultSecurityConfiguration.php on line 136

**Comment by Limbo0x01** [comment]
[SOLVED]

**Comment by an20202482** [comment]
Warning: mysqli::__construct(): (HY000/2002): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution in /var/www/html/mutillidae/classes/MySQLHandler.php on line 136
Connected to MySQL server at 127.0.0.1 as root
Preparing to drop database mutillidae

Warning: mysqli::query(): Couldn't fetch mysqli in /var/www/html/mutillidae/classes/MySQLHandler.php on line 230

Warning: MySQLHandler::serializeMySQLImprovedObjectProperties(): Couldn't fetch mysqli in /var/www/html/mutillidae/classes/MySQLHandler.php on line 207

Warning: MySQLHandler::serializeMySQLImprovedObjectProperties(): Couldn't fetch mysqli in /var/www/html/mutillidae/classes/MySQLHandler.php on line 211

Warning: MySQLHandler::serializeMySQLImprovedObjectProperties(): Property access is not allowed yet in /var/www/html/mutillidae/classes/MySQLHandler.php on line 215

Warning: MySQLHandler::serializeMySQLImprovedObjectProperties(): Couldn't fetch mysqli in /var/www/html/mutillidae/classes/MySQLHandler.php on line 219
Error was reported while attempting to drop database mutillidae
MySQL sometimes throws errors attempting to drop databases. Here is error in case the error is serious.
Error Message


 i have the same here
